export const yearOptions = [
  { label: "2004", value: "2004" },
  { label: "2003", value: "2003" },
  { label: "2002", value: "2002" },
  { label: "2001", value: "2001" },
  { label: "2000", value: "2000" },
  { label: "1999", value: "1999" },
  { label: "1998", value: "1998" },
  { label: "1997", value: "1997" },
  { label: "1996", value: "1996" },
  { label: "1995", value: "1995" },
  { label: "1994", value: "1994" },
  { label: "1993", value: "1993" },
  { label: "1992", value: "1992" },
  { label: "1991", value: "1991" },
  { label: "1990", value: "1990" },
];

export const monthOptions = [
  { label: "January", value: "01" },
  { label: "February", value: "02" },
  { label: "March", value: "03" },
  { label: "April", value: "04" },
  { label: "May", value: "05" },
  { label: "Juin", value: "06" },
  { label: "July", value: "07" },
  { label: "August", value: "08" },
  { label: "September", value: "09" },
  { label: "October", value: "10" },
  { label: "November", value: "11" },
  { label: "December", value: "12" },
];

export const _30dayOptions = [
  { label: "01", value: "01" },
  { label: "02", value: "02" },
  { label: "03", value: "03" },
  { label: "04", value: "04" },
  { label: "05", value: "05" },
  { label: "06", value: "06" },
  { label: "07", value: "07" },
  { label: "08", value: "08" },
  { label: "09", value: "09" },
  { label: "10", value: "10" },
  { label: "11", value: "11" },
  { label: "12", value: "12" },
  { label: "13", value: "13" },
  { label: "14", value: "14" },
  { label: "15", value: "15" },
  { label: "16", value: "16" },
  { label: "17", value: "17" },
  { label: "18", value: "18" },
  { label: "19", value: "19" },
  { label: "20", value: "20" },
  { label: "21", value: "21" },
  { label: "22", value: "22" },
  { label: "23", value: "23" },
  { label: "24", value: "24" },
  { label: "25", value: "25" },
  { label: "26", value: "26" },
  { label: "27", value: "27" },
  { label: "28", value: "28" },
  { label: "29", value: "29" },
  { label: "30", value: "30" },
];
export const _31dayOptions = [
  { label: "01", value: "01" },
  { label: "02", value: "02" },
  { label: "03", value: "03" },
  { label: "04", value: "04" },
  { label: "05", value: "05" },
  { label: "06", value: "06" },
  { label: "07", value: "07" },
  { label: "08", value: "08" },
  { label: "09", value: "09" },
  { label: "10", value: "10" },
  { label: "11", value: "11" },
  { label: "12", value: "12" },
  { label: "13", value: "13" },
  { label: "14", value: "14" },
  { label: "15", value: "15" },
  { label: "16", value: "16" },
  { label: "17", value: "17" },
  { label: "18", value: "18" },
  { label: "19", value: "19" },
  { label: "20", value: "20" },
  { label: "21", value: "21" },
  { label: "22", value: "22" },
  { label: "23", value: "23" },
  { label: "24", value: "24" },
  { label: "25", value: "25" },
  { label: "26", value: "26" },
  { label: "27", value: "27" },
  { label: "28", value: "28" },
  { label: "29", value: "29" },
  { label: "30", value: "30" },
  { label: "31", value: "31" },
];
export const _29dayOptions = [
  { label: "01", value: "01" },
  { label: "02", value: "02" },
  { label: "03", value: "03" },
  { label: "04", value: "04" },
  { label: "05", value: "05" },
  { label: "06", value: "06" },
  { label: "07", value: "07" },
  { label: "08", value: "08" },
  { label: "09", value: "09" },
  { label: "10", value: "10" },
  { label: "11", value: "11" },
  { label: "12", value: "12" },
  { label: "13", value: "13" },
  { label: "14", value: "14" },
  { label: "15", value: "15" },
  { label: "16", value: "16" },
  { label: "17", value: "17" },
  { label: "18", value: "18" },
  { label: "19", value: "19" },
  { label: "20", value: "20" },
  { label: "21", value: "21" },
  { label: "22", value: "22" },
  { label: "23", value: "23" },
  { label: "24", value: "24" },
  { label: "25", value: "25" },
  { label: "26", value: "26" },
  { label: "27", value: "27" },
  { label: "28", value: "28" },
  { label: "29", value: "29" },
];

export const _28dayOptions = [
  { label: "01", value: "01" },
  { label: "02", value: "02" },
  { label: "03", value: "03" },
  { label: "04", value: "04" },
  { label: "05", value: "05" },
  { label: "06", value: "06" },
  { label: "07", value: "07" },
  { label: "08", value: "08" },
  { label: "09", value: "09" },
  { label: "10", value: "10" },
  { label: "11", value: "11" },
  { label: "12", value: "12" },
  { label: "13", value: "13" },
  { label: "14", value: "14" },
  { label: "15", value: "15" },
  { label: "16", value: "16" },
  { label: "17", value: "17" },
  { label: "18", value: "18" },
  { label: "19", value: "19" },
  { label: "20", value: "20" },
  { label: "21", value: "21" },
  { label: "22", value: "22" },
  { label: "23", value: "23" },
  { label: "24", value: "24" },
  { label: "25", value: "25" },
  { label: "26", value: "26" },
  { label: "27", value: "27" },
  { label: "28", value: "28" },
];

export const dayOptions = (year: string, month: string) => {
  if (
    month == "01" ||
    month == "03" ||
    month == "05" ||
    month == "07" ||
    month == "08" ||
    month == "10" ||
    month == "12"
  ) {
    return _31dayOptions;
  } else if (month == "02") {
    if (parseInt(year) % 4 == 0 && parseInt(year) % 100 != 0) {
      return _29dayOptions;
    } else {
      return _28dayOptions;
    }
  } else {
    return _30dayOptions;
  }
};

export const cityOptions = [
  { label: "Partout au Maroc", value: "Everywhere" },
  { label: "Casablanca", value: "Casablanca" },
  { label: "Fez", value: "Fez" },
  { label: "Tangier", value: "Tangier" },
  { label: "Marrakech", value: "Marrakech" },
  { label: "Salé", value: "Salé" },
  { label: "Rabat", value: "Rabat" },
  { label: "Meknes", value: "Meknes" },
  { label: "Oujda", value: "Oujda" },
  { label: "Kenitra", value: "Kenitra" },
  { label: "Agadir", value: "Agadir" },
  { label: "Tetouan", value: "Tetouan" },
  { label: "Temara", value: "Temara" },
  { label: "Safi", value: "Safi" },
  { label: "Mohammedia", value: "Mohammedia" },
  { label: "Khouribga", value: "Khouribga" },
  { label: "El Jadida", value: "El Jadida" },
  { label: "Beni Mellal", value: "Beni Mellal" },
  { label: "Nador", value: "Nador" },
  { label: "Settat", value: "Settat" },
  { label: "Taza", value: "Taza" },
  { label: "Berrechid", value: "Berrechid" },
  { label: "Khmisset", value: "Khmisset" },
  { label: "Guelmim", value: "Guelmim" },
  { label: "Larache", value: "Larache" },
  { label: "Khenifra", value: "Khenifra" },
  { label: "Ben guerir", value: "Ben guerir" },
  { label: "Essaouira", value: "Essaouira" },
  { label: "Ouarzazate", value: "Ouarzazate" },
];
export const jobOptions = [
  { label: "Developpeur", value: "Developper" },
  { label: "Editeur", value: "Editor" },
  { label: "Cuisinier", value: "Chef" },
  { label: "Plombier", value: "Plumber" },
  { label: "Electricien", value: "Electrician" },
  { label: "Coiffeur", value: "Barber" },
  { label: "Tailleur", value: "Tailor" },
  { label: "Photographe", value: "Photographer" },
  { label: "Menuisier", value: "Carpenter" },
  { label: "Forgeron", value: "BlackSmith" },
  { label: "Peintre", value: "Painter" },
  { label: "Platrier", value: "plasterer" },
  { label: "Chauffeur", value: "Driver" },
  { label: "Femme de ménage", value: "Housemaid" },
  { label: "Tuteur", value: "Tutor" },
  { label: "Entraîneur", value: "Coach" },
];
export const durationOptions = [
  { label: "Not specified", value: 24 * 32 },
  { label: "1 hour", value: 1 },
  { label: "2 hours", value: 2 },
  { label: "3 hours", value: 3 },
  { label: "4 hours", value: 4 },
  { label: "5 hours", value: 5 },
  { label: "6 hours", value: 6 },
  { label: "7 hours", value: 7 },
  { label: "8 hours", value: 8 },
  { label: "9 hours", value: 9 },
  { label: "10 hours", value: 10 },
  { label: "11 hours", value: 11 },
  { label: "12 hours", value: 12 },
  { label: "1 day", value: 24 * 1 },
  { label: "2 days", value: 24 * 2 },
  { label: "3 days", value: 24 * 3 },
  { label: "4 days", value: 24 * 4 },
  { label: "5 days", value: 24 * 5 },
  { label: "6 days", value: 24 * 6 },
  { label: "7 days", value: 24 * 7 },
  { label: "8 days", value: 24 * 8 },
  { label: "9 days", value: 24 * 9 },
  { label: "10 days", value: 24 * 10 },
  { label: "11 day1", value: 24 * 11 },
  { label: "12 days", value: 24 * 12 },
  { label: "13 days", value: 24 * 13 },
  { label: "14 days", value: 24 * 14 },
  { label: "15 days", value: 24 * 15 },
  { label: "16 days", value: 24 * 16 },
  { label: "17 days", value: 24 * 17 },
  { label: "18 days", value: 24 * 18 },
  { label: "19 days", value: 24 * 19 },
  { label: "20 days", value: 24 * 20 },
  { label: "21 days", value: 24 * 21 },
  { label: "22 days", value: 24 * 22 },
  { label: "23 days", value: 24 * 23 },
  { label: "24 days", value: 24 * 24 },
  { label: "25 days", value: 24 * 25 },
  { label: "26 days", value: 24 * 26 },
  { label: "27 days", value: 24 * 27 },
  { label: "28 days", value: 24 * 28 },
  { label: "29 days", value: 24 * 29 },
  { label: "30 days", value: 24 * 30 },
  { label: "more than 30 days", value: 24 * 31 },
];
